from youtube_transcript_api import YouTubeTranscriptApi
import json

print(YouTubeTranscriptApi.get_transcript("P_6vDLq64gE"))
transcript_list = YouTubeTranscriptApi.list_transcripts("P_6vDLq64gE")
print(transcript_list)
with open('examples/file1.json', 'w', encoding='utf-8') as f:
    json.dump(YouTubeTranscriptApi.get_transcripts(["iCvmsMzlF7o"], languages=['uk']), f, ensure_ascii=False)

transcript = transcript_list.find_transcript(['de', 'en'])
print(transcript)
transcript = transcript_list.find_manually_created_transcript(['uk'])
print(transcript.is_generated)

print(
    transcript.video_id,
    transcript.language,
    transcript.language_code,
    # whether it has been manually created or generated by YouTube
    transcript.is_generated,
    # whether this transcript can be translated or not
    transcript.is_translatable,
    # a list of languages the transcript can be translated to
    transcript.translation_languages,
)
transcript.fetch()
